version: "3.6"

services:

  db:
    image: postgres:14.5
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=KY9CO8sHshzM5YxfLtzL
    volumes:
      - datadb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 1s
      retries: 6
      start_period: 5s

  iam:
    image: quay.io/keycloak/keycloak:18.0.2
    environment:
      - KEYCLOAK_ADMIN=armoire
      - KEYCLOAK_ADMIN_PASSWORD=vBWtB2PloopC042cszXZ
      - KC_HTTPS_CERTIFICATE_FILE=/run/secrets/crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/run/secrets/key
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=KY9CO8sHshzM5YxfLtzL
    command:
      - start-dev
      - --hostname=dockereni.francecentral.cloudapp.azure.com
    secrets:
      - crt
      - key
    ports:
      - "443:8443"

volumes:
  datadb:
    driver: local

secrets:
  crt:
    file: /home/azureuser/server.crt.pem
  key:
    file: /home/azureuser/server.key.pem
